services:
  - type: web
    name: zisk-connect
    env: node
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 22
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DB
        value: zisk_connect
      - key: SESSION_SECRET
        generateValue: true
